# Fichier de base de données
database_file: database.db

# Module web
web:
  host: 127.0.0.1 # IP d'écoute (0.0.0.0 pour toutes les IP)
  port: 9999 # Port d'écoute

# URL de base du serveur
web_base: http://127.0.0.1:9999

# Clé secrète Flask
web_secret_key: qwertyuiop1234567890

# Répertoires
directories:
  # Répertoire contenant les images de l'app (sans le slash final)
  images: images
  # Répertoire contenant les médias transcodés (sans le slash final)
  medias: medias
  # Répertoire contenant les médias temporaires en attente de transcodage (sans le flash final)
  mediasTmp: tmp_medias


# Paramètres de transcodage
transcoding:
  maxRetry: 20

# Paramètres des conducteurs
conductors:
  # Heure à laquelle le nettoyage des conducteurs doit s'opérer
  cleanerSchedule: 4
  # Ancienneté maximale des conducteurs en jours pour la suppression automatique
  retention: 90


# Contraintes de liens
linksConstraints:
  # pour chaque contrainte :
  # - pattern: regexp permettant de déclencher la contrainte
  #   ignoreCase: true/false. Définit si le pattern est ignore ou non la casse
  #   description: une description, pour vous y retrouver
  #   refuse: true/false. Défini si le lien doit être refusé ou pas
  #   alert: "alerte à afficher si le pattern est trouvé. Vous pouvez mettre $x pour insérer une capture x du pattern. Utilisez $Ux pour appliquer un encodage URL sur la capture."

  - pattern: ^(?!https?:\/\/\S+\.\S+).*$
    ignoreCase: true
    description: Liens valides
    refuse: true
    alert: "Lien refusé. Cet URL n'est pas un lien valide."

  - pattern: ^https?://cdn\.discordapp\.com/.*$
    ignoreCase: true
    description: Liens CDN Discord.
    refuse: true
    alert: "Lien refusé. Merci de télécharger cette image ou vidéo Discord dans le conducteur en tant que média."

  - pattern: ^https?://(www\.)?youtube\.com/watch\?v=([a-zA-Z0-9-_]+).*$
    ignoreCase: true
    description: Liens vidéos YouTube.
    refuse: false
    alert: "Vidéo YouTube détectée ! Merci de télécharger la vidéo. Vous pouvez télécharger la vidéo ici : https://y2mate.is/watch?v=$2"

  - pattern: ^https?://(www\.)?youtu\.be/([a-zA-Z0-9_-]+).*$
    ignoreCase: true
    description: Liens vidéos YouTube (lien court).
    refuse: false
    alert: "Vidéo YouTube détectée ! Merci de télécharger la vidéo. Vous pouvez télécharger la vidéo ici : https://y2mate.is/watch?v=$2"

  - pattern: ^https?://(www\.)?(x|twitter)\.com/.*/status/.*$
    ignoreCase: true
    description: Liens vers un tweet.
    refuse: false
    alert: "Si le contenu important dans le tweet est une photo ou une vidéo, merci de la télécharger au lieu d'utiliser un lien."

  - pattern: ^https?://(www\.)?(x|twitter)\.com/.*/status/.*$
    ignoreCase: true
    description: Liens vers un tweet.
    refuse: false
    alert: "Si le contenu important dans le tweet est une photo ou une vidéo, merci de la télécharger au lieu d'utiliser un lien."

  - pattern: ^https?://(www\.)?(x|twitter)\.com/.*/photo/.*$
    ignoreCase: true
    description: Liens vers la photo d'un tweet.
    refuse: true
    alert: "Lien refusé. Merci de télécharger l'image dans le conducteur en tant que média."

  - pattern: ^https?://pbs\.twimg\.com/.*$
    ignoreCase: true
    description: Lien vers un asset sur le CDN Twitter.
    refuse: true
    alert: "Lien refusé. Merci de télécharger l'image ou la vidéo dans le conducteur en tant que média."

  - pattern: ^https?://(www\.)?instagram\.com/p/.*$
    ignoreCase: true
    description: Lien vers un post instagram.
    refuse: false
    alert: "Merci de télécharger ce post Instagram dans le conducteur en tant que média."

  - pattern: ^https?://(www\.)?facebook\.com/.*/posts/.*$
    ignoreCase: true
    description: Lien vers un post Facebook.
    refuse: false
    alert: "S'il s'agit d'un post Facebook contenant une photo ou une vidéo, merci de la télécharger dans le conducteur en tant que média."

  - pattern: ^https?://(www\.)?facebook\.com/photo.*$
    ignoreCase: true
    description: Lien vers une photo Facebook.
    refuse: true
    alert: "Lien refusé. Merci de télécharger cette photo Facebook dans le conducteur en tant que média."

  - pattern: ^https?://.*\.fbcdn\.net/.*$
    ignoreCase: true
    description: Lien vers un asset sur le CDN Facebook.
    refuse: true
    alert: "Lien refusé. Merci de télécharger cette photo ou cette vidéo Facebook dans le conducteur en tant que média."

  - pattern: ^https?://(www\.)?facebook\.com/.*/videos/.*$
    ignoreCase: true
    description: Lien vers une vidéo Facebook.
    refuse: false
    alert: "Merci de télécharger cette vidéo Facebook dans le conducteur en tant que média."

  - pattern: ^https?://(www\.)?tiktok\.com/.*/video/.*$
    ignoreCase: true
    description: Lien vers une vidéo TikTok.
    refuse: false
    alert: "Merci de télécharger cette vidéo TikTok dans le conducteur en tant que média."

  - pattern: ^https?://(www\.)?linkedin\.com/posts/.*$
    ignoreCase: true
    description: Lien vers un post LinkedIn.
    refuse: false
    alert: "Si le contenu important dans ce post LinkedIn est une image ou une vidéo, merci de la télécharger dans le conducteur en tant que média. Si vous souhaitez diffuser le post entier, merci de privilégier les captures d'écran."

  - pattern: ^.*\.(jpg|jpeg|png|webp)(\?.*)?$
    ignoreCase: true
    description: Lien direct vers une image.
    refuse: true
    alert: "Lien refusé. Merci de télécharger cette image dans le conducteur en tant que média."

  - pattern: ^.*\.(mp4|webm|mov|avi)(\?.*)?$
    ignoreCase: true
    description: Lien direct vers une vidéo.
    refuse: true
    alert: "Lien refusé. Merci de télécharger cette vidéo dans le conducteur en tant que média."

  - pattern: ^http://.*$
    ignoreCase: true
    description: Liens non HTTPS.
    refuse: false
    alert: "Préférez les liens https au lieu de http."
